### ISSUE TITLE
Portis option not working on Connect Wallet V2 Yearn.

### ISSUE THREAD

**Issue by 5BoLT** [yearn/yearn-vaults-v1#102]
### What's your issue about?
I recently tried to connect my wallet on to yearn and found out the Portis option is not working. Luckily V1 is still up and works! Just a heads-up!

**Comment by fubuloubu** [comment]
I think this issue is better off in the Web UI repo: https://github.com/iearn-finance/iearn-finance

This repository is for the Yearn v1 smart contracts.

**Comment by saltyfacu** [comment]
Moved to: https://github.com/iearn-finance/iearn-finance/issues/246
