### ISSUE TITLE
HouseKeeping add updated crvEur strategy

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-vaults-v1#104]
HouseKeeping add crvEUR strategy latest update from this address:
0x83e7399113561ae691c413ed334137D3839e2302

Should follow similar house keeping PRs including:
* refactoring interfaces
* update calls in code to use interfaces
* CI should be green before merging

Example PRs to follow
https://github.com/iearn-finance/yearn-protocol/pull/89/files

**Comment by ghost** [comment]
will help
