### ISSUE TITLE
HouseKeeping add updated crvPBTC strategy

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-vaults-v1#105]
HouseKeeping add crvPBTC strategy latest update from this address:
0x123964EbE096A920dae00Fb795FFBfA0c9Ff4675

Should follow similar housekeeping PRs including:

- Refactoring interfaces
- Update calls in code to use interfaces
- CI should be green before merging

**Example PRs to follow**
https://github.com/iearn-finance/yearn-protocol/pull/89/files

**Comment by ghost** [comment]
crvPBTC, crvOBTC, crvTBTC and crvsUSD are all the exact same contract initiated with different parameters.
#106 
#107 
#108

**Comment by saltyfacu** [comment]
Repository is superseded by [yearn-vaults](https://github.com/yearn/yearn-vaults)
