### ISSUE TITLE
HouseKeeping several Curve Strategies

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-vaults-v1#111]
[StrategyCurvesUSDVoterProxy](https://github.com/iearn-finance/yearn-protocol/pull/90)

[StrategyCurveTBTCVoterProxy](https://github.com/iearn-finance/yearn-protocol/pull/91)

[StrategyCurvePBTCVoterProxy](https://github.com/iearn-finance/yearn-protocol/pull/93)

[StrategyCurveOBTCVoterProxy](https://github.com/iearn-finance/yearn-protocol/pull/94)

TODO: housekeeping

**Comment by saltyfacu** [comment]
Repository is superseded by [yearn-vaults](https://github.com/yearn/yearn-vaults)
