### ISSUE TITLE
How can I calculate Busd APY

### ISSUE THREAD

**Issue by hyunkicho** [yearn/yearn-vaults-v1#112]
![image](https://user-images.githubusercontent.com/35443121/112104916-1a52a300-8bef-11eb-879a-8ac1bda7fbca.png)
Hi I want to know how can I calculate this APY displayed at above screenshot. 
I'd be appreciate if u could show me on BUSD

**Comment by saltyfacu** [comment]
Hi! That's related to the frontend. You can ask on Discord or create new issue in the frontend repo: https://github.com/yearn/yearn-finance
