### ISSUE TITLE
my issue

### ISSUE THREAD

**Issue by khelan76** [yearn/yearn-vaults-v1#117]
Hello
Please help me get back my tokens that I sent by mistake to hold liquidity 26.14 WBNB & 14,314.328390163716407215 SISHI Back to my wallet 0x261DF701BC42dED68A367B0bC74D3C67BfD3C642
And this is my proof 0xb2bb4af51713470677b52c78bf345d0388b87685d7d8120fc1eba4dde8885501
0xd5b59ced3676c10dc7020062140e11db033449fc0c872318feaa3ad7ea0214a0
please help me
Transaction done on the blockchain can be reversed Please send it to me again
I sendet to this Contract 0xf0A9Af2aEF77d903fc86D3B08BdFCf87f0088A8E

**Comment by dudesahn** [comment]
Hi, this appears to be a vault that belongs to another protocol, Sishi Finance. We have no control over it. Please reach out to the Sishi Finance team—I checked their website and this appears to be their telegram: https://t.me/sishi_finance. Good luck!
