### ISSUE TITLE
StrategyYFIGovernance can't vote

### ISSUE THREAD

**Issue by banteg** [yearn/yearn-vaults-v1#15]
`strategy` doesn't register itself as a voter in `ygov`, so `strategy.voteFor()` and `strategy.voteAgainst()` have no effect.

to fix this `strategy` should call `ygov.register()` to be able to vote.

the original idea was for it to be an emergency quorum trigger, only callable by `governance`.

this issue can probably be marked as wontfix, since we are redoing governance anyway.

```
strategy = 0x395F93350D5102B6139Abfc84a7D6ee70488797C
ygov = 0xBa37B002AbaFDd8E89a1995dA52740bbC013D992
```

**Comment by banteg** [comment]
It also misses `getName()`

**Comment by storming0x** [comment]
is this good to close since i believe its being discussed in yearn v2?

**Comment by saltyfacu** [comment]
According to Doggie's feedback, no longer relevant.
