### ISSUE TITLE
Wallet connection issues

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-vaults-v1#23]
Argent with walletconnect not working, was working a week ago now giving the following error "index.ts:181 Uncaught (in promise) TypeError: this.send is not a function"  right after connecting and not working afterwards.

**Comment by DarkGhost7** [comment]
Please leave you issues in the form
{wallet used} 
{which connection method: (trustwallet / walletconnect ect} 
{which os: android, ios, pc, mac}
{error msg, picture if you have one}

**Comment by fubuloubu** [comment]
Hello @DarkGhost7, your issue is with https://github.com/iearn-finance/iearn-finance instead. Please open an issue there.

**Comment by DarkGhost7** [comment]
ohh sorry

**Comment by fubuloubu** [comment]
No worries!
