### ISSUE TITLE
Add xdist support

### ISSUE THREAD

**Issue by milkyklim** [yearn/yearn-vaults-v1#26]
Adding isolation to test drastically speeds up CI: https://eth-brownie.readthedocs.io/en/stable/tests-pytest-intro.html#pytest-fixtures-isolation

**Comment by ShadeUndertree** [comment]
I can pick this one up.

**Comment by ShadeUndertree** [comment]
See https://github.com/iearn-finance/yearn-protocol/pull/42, note that adding xdist support without a destructive level of test indirection can actually cause these tests to run slower, depending on your machine and load.

**Comment by ShadeUndertree** [comment]
Given that we've got this in place for v2 vaults this is probably safe to close.
