### ISSUE TITLE
Add slither support 

### ISSUE THREAD

**Issue by milkyklim** [yearn/yearn-vaults-v1#28]
See https://github.com/crytic/slither

**Comment by Macarse** [comment]
I have been digging a bit about this issue.

More info:
 - https://github.com/crytic/slither/issues/638
 - https://github.com/eth-brownie/brownie/issues/772

**Comment by saltyfacu** [comment]
Repository is superseded by [yearn-vaults](https://github.com/yearn/yearn-vaults)
