### ISSUE TITLE
Add minimal README.md

### ISSUE THREAD

**Issue by milkyklim** [yearn/yearn-vaults-v1#33]
At least include:

- [ ] description 
- [ ] how-to run/test

ref: https://github.com/iearn-finance/yearn-protocol/pull/27#discussion_r499145835

**Comment by hjvsantos** [comment]
I'm interested to do this, Can you assign this

**Comment by lbertenasco** [comment]
Linking @dmolina79 's PR to the issue: https://github.com/iearn-finance/yearn-protocol/pull/35
