### ISSUE TITLE
Deployment document for mainnet (step-by-step)

### ISSUE THREAD

**Issue by mindfulme** [yearn/yearn-vaults-v1#38]
Can we do a simple step-by-step deployment guide for newbies to play around yearn protocol and learn around yearn smart contracts on practice? 

Would be helpful to learn about vaults on mainnet by having a full guide on deploying vaults and adding new vaults to yearn protocol.

**Comment by mindfulme** [comment]
Is there a deployment script? https://eth-brownie.readthedocs.io/en/stable/deploy.html

**Comment by mindfulme** [comment]
or the basics of brownie will be enough? https://medium.com/better-programming/part-1-brownie-smart-contracts-framework-for-ethereum-basics-5efc80205413

**Comment by fubuloubu** [comment]
The deployment process is currently very specialized, but part of the refresh we are doing for v2 will include deployment scripts.

Brownie can help you out for now.

**Comment by saltyfacu** [comment]
We are polishing the document here on how to deploy V2 vaults here: https://github.com/iearn-finance/yearn-vaults/pull/181

**Comment by saltyfacu** [comment]
We have the first version of the operations manual ready here: https://github.com/iearn-finance/yearn-vaults/blob/master/docs/OPERATIONS.md
