### ISSUE TITLE
First vault added to release a new apiVersion is always endorsed

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-vaults-v1#96]
### What's your issue about?
The vault that is used to create a new release using YRegistry.newRelease(0x...) is automatically endorsed and shown on Yearn's main site in the production tab.

**Steps to reproduce**
Create a new release using YRegistry.newRelease(0x...) with any vault.

**What is expected to happen.**
It's expected to create a new release and add the vault to the registry. 

**What actually happens.**
It creates a new release, adds the vault to the registry, and endorses it automatically.

**Notes**
It's not always that the first vault of a new release is production-ready. So we need a way to create a new release, add a vault, and test it accordingly.

**Comment by fubuloubu** [comment]
Closing in favor of https://github.com/iearn-finance/yearn-vaults/issues/179
